[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Client"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_client"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.85.2"

[features]
default=[]
local-discovery=["sn_networking/local-discovery"]

[dependencies]
async-trait = "0.1"
bincode = "1.3.1"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
futures = "~0.3.13"
indicatif = { version = "0.17.5", features = ["tokio"] }
itertools = "~0.10.1"
libp2p = { version="0.51", features = ["identify"] }
rand = { version = "~0.8.5", features = ["small_rng"] }
rayon = "~1.5.1"
self_encryption = "~0.28.0"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
sn_dbc = { version = "19.0.0", features = ["serdes"] }
sn_networking = { path = "../sn_networking", version = "0.1.1" }
sn_protocol = { path = "../sn_protocol", version = "0.1.1" }
sn_registers = { path = "../sn_registers", version = "0.1.1" }
sn_transfers = { path = "../sn_transfers", version = "0.1.0" }
thiserror = "1.0.23"
tiny-keccak = "~2.0.2"
tokio = { version = "1.17.0", features = ["fs", "io-util", "macros", "parking_lot", "rt", "sync", "time"] }
tracing = { version = "~0.1.26" }
xor_name = "5.0.0"

